# Generated by Django 5.0.3 on 2024-04-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebHeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_name', models.CharField(max_length=15)),
                ('primer_lastname', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('tel', models.CharField(max_length=15)),
            ],
        ),
    ]
